language: java
install: true
dist: xenial

script:
 - ./gradlew build --scan -s -PmavenUser=${mavenUser} -PmavenPassword=${mavenPassword} -Psigning.keyId=${GPG_KEY_ID} Psigning.password=${GPG_KEY_PASSPHRASE} -Psigning.secretKeyRingFile=travis.gpg
 - ./gradlew publish -PmavenUser=${mavenUser} -PmavenPassword=${mavenPassword} -Psigning.keyId=${GPG_KEY_ID} Psigning.password=${GPG_KEY_PASSPHRASE} -Psigning.secretKeyRingFile=travis.gpg

before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
 - chmod +x gradlew
 - sudo gem install travis
 - gpg --export-secret-key ${GPG_KEY_ID} > travis.gpg
 - travis encrypt-file travis.jpg
 - shred --remove travis.gpg
 - ./gradlew wrapper

jdk: oraclejdk11

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $TCLRAINBOW
  - ./send.sh success $Sanjay
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $TCLRAINBOW
  - ./send.sh failure $Sanjay
